name: sklad_helper
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  
  # --- Localization ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # --- Firebase Core & Auth ---
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.2.10

  # --- Social Login ---
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2

  # --- Architecture & Navigation ---
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7

  # --- Network & APIs (Push Sender) ---
  http: ^1.6.0
  googleapis_auth: ^2.0.0

  # --- Files & Data Processing ---
  shared_preferences: ^2.3.2
  file_picker: ^10.3.10
  desktop_drop: ^0.7.0
  cross_file: ^0.3.5+2
  excel: ^4.0.6
  spreadsheet_decoder: ^2.3.0

  # --- UI & Utilities ---
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.2.3
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  # ВАЖНО: Добавлена папка assets для ключа
  assets:
    - assets/service_account.json